# Generated by Django 3.2.5 on 2021-07-11 14:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=200)),
                ('release_date', models.DateTimeField()),
                ('already_bought', models.BooleanField()),
            ],
        ),
    ]
